import type { Metadata } from "next";
// import "normalize.css";
import "./globals.css";
import '@my-own-blog/core/lib/date/date.extensions.ts';
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import Header from "@/components/Header";
import Providers from '@my-own-blog/core/lib/Providers';
import localFont from "next/font/local";

config.autoAddCss = false;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const myFont = localFont({ src: "../asset/spoqa.woff2" });
import { Nanum_Myeongjo } from 'next/font/google' // 해당 폰트의 함수를 사용합니다.
const font = Nanum_Myeongjo({
  subsets: ['latin'],
  weight: "400"
})
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={"flex flex-col " + font.className}>
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
