services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      .env
    volumes:
      - /docker/mysql:/var/lib/mysql
    container_name: prisma-mysql
    ports:
      - 3306:3306
      
  object_storage:
    image: quay.io/minio/minio
    container_name: minio_storage
    restart: always
    command: server /minio --console-address ":9001"
    env_file:
      .env
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - /docker/minio:/minio