import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { DragDropContext } from "react-beautiful-dnd";
import { useCallback } from "react";
import { resetServerContext } from 'react-beautiful-dnd';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      
        <body className={inter.className}>
          <Navbar>{children}</Navbar>
        </body>
    </html>
  );
}
