name: Docker CI

on:
  push:
    branches: [master]
jobs:
  deploy:
    name: Build and push to ghcr.io
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        node-version: [21.1.0]
    environment: Production
    steps:
      - name: check if envs exist
        run: echo ${{secrets.DATABASE_URL}}

      - name: Clone code from github
        uses: actions/checkout@v3

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            "DATABASE_URL=${{ secrets.DATABASE_URL }}"
            "MINIO_URL=${{secrets.MINIO_URL}}"
            "MINIO_ACCESS_KEY=${{secrets.MINIO_ACCESS_KEY}}"
            "MINIO_PRIVATE_KEY=${{secrets.MINIO_PRIVATE_KEY}}"
