name: Docker CI

on:
  push:
    branches: [master]
jobs:
  deploy:
    name: Build and push to ghcr.io
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        node-version: [21.1.0]
    environment: Production
    permissions: write-all
    steps:
      - name: Clone code from github
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: KimWash
          password: ${{secrets.GITHUB_TOKEN}}

      # - name: Build and push
      #   uses: docker/build-push-action@v2
      #   with:
      #     push: true
      #     tags: ghcr.io/kimwash/blog.kimwash.xyz:master
      #     context: .
      #     file: ./Dockerfile
      #     build-args: |
      #       "DATABASE_URL=${{ secrets.DATABASE_URL }}"
      #       "MINIO_URL=${{secrets.MINIO_URL}}"
      #       "MINIO_ACCESS_KEY=${{secrets.MINIO_ACCESS_KEY}}"
      #       "MINIO_PRIVATE_KEY=${{secrets.MINIO_PRIVATE_KEY}}"
